<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ivW1cU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ivW1cU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5ivW1cU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5ivW1cU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5ivW1cU\App_KernelDevDebugContainer([
    'container.build_hash' => '5ivW1cU',
    'container.build_id' => '4fe11706',
    'container.build_time' => 1616160087,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ivW1cU');
