<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqiOiVC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqiOiVC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXqiOiVC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXqiOiVC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXqiOiVC\App_KernelDevDebugContainer([
    'container.build_hash' => 'XqiOiVC',
    'container.build_id' => '6362c494',
    'container.build_time' => 1616508802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqiOiVC');
